owner: d33bs
repo: upptime-curc

sites:
  - name: CURC Website
    url: https://www.colorado.edu/rc
  - name: CURC Docs
    url: https://curc.readthedocs.io/en/latest/
  - name: Alpine (CURC Page)
    url: https://www.colorado.edu/rc/alpine
  - name: Globus
    url: https://www.globus.org
  - name: ACCESS
    url: https://access-ci.org
  - name: XSEDE Redirect
    url: https://www.xsede.org

status-website:
  baseUrl: /upptime-curc
  name: CU Research Computing Status
  introTitle: "CU Research Computing Service Status"
  introMessage: "Automated uptime and response-time monitoring for key CU Research Computing resources."
  navbar:
    - title: Status
      href: /
    - title: CURC
      href: https://www.colorado.edu/rc
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "0 * * * *"
  responseTime: "0 * * * *"
