owner: d33bs
repo: upptime-curc

sites:
  - name: CURC Statuspage Alpine Component
    url: https://curc.statuspage.io/api/v2/summary.json
    __dangerous__body_down_if_text_missing: '"name":"Alpine","status":"operational"'
    notifications:
      - type: discord
        url: $DISCORD_WEBHOOK_ALPINE
  - name: 📈 CURC XDMoD Alpine Utilization Threshold
    url: https://raw.githubusercontent.com/d33bs/upptime-curc/HEAD/api/curc-xdmod-alpine-utilization-threshold/status.json
    icon: https://xdmod.rc.colorado.edu/gui/icons/favicon_static.ico
    __dangerous__body_down_if_text_missing: '"status": "UP"'
    notifications:
      - type: discord
        url: $DISCORD_WEBHOOK_ALPINE
  - name: ⛰️🚪 Alpine Login Node SSH (TCP Reachability)
    check: tcp-ping
    url: login.rc.colorado.edu
    port: 22
    notifications:
      - type: discord
        url: $DISCORD_WEBHOOK_ALPINE
  - name: Alpine CURC Page
    url: https://www.colorado.edu/rc/alpine
    notifications:
      - type: discord
        url: $DISCORD_WEBHOOK_ALPINE
  - name: CURC Open OnDemand HTTPS (TCP Reachability)
    check: tcp-ping
    url: ondemand.rc.colorado.edu
    port: 443
  - name: CURC Data Transfer Node SSH (TCP Reachability)
    check: tcp-ping
    url: dtn.rc.colorado.edu
    port: 22
  - name: CURC Docs (Public Webpage)
    url: https://curc.readthedocs.io/en/latest/
  - name: Globus Transfer API (Technical Endpoint)
    url: https://transfer.api.globus.org
  - name: ACCESS Registry (Technical Endpoint)
    url: https://registry.access-ci.org/registry/
  - name: Globus Website (Public Webpage)
    url: https://www.globus.org
  - name: ACCESS Website (Public Webpage)
    url: https://access-ci.org

status-website:
  baseUrl: /upptime-curc
  name: CU Research Computing Status
  introTitle: "CU Research Computing Access Status"
  introMessage: "Automated monitoring for practical user access points (login, Open OnDemand, data transfer), plus CURC docs and partner technical endpoints."
  navbar:
    - title: Status
      href: /
    - title: CURC
      href: https://www.colorado.edu/rc
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "0 * * * *"
  responseTime: "0 * * * *"
